spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/cafree
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

  logging.level:
    org:
      hibernate:
        SQL: debug
        type: trace


cloud:
  aws:
    region:
      static:
        ap-northeast-2
    s3-bucket:
      cafree-prod
    credentials:
      access-key: ${S3-ACCESS-KEY}
      secret-key: ${S3-SECRET-KEY}
    stack:
      auto:
        false